---
- name: reload bind9
  service:
    name: named
    state: reloaded

- name: restart bind9
  service:
    name: named
    state: restarted

- name: restart bind_exporter
  systemd:
    name: bind_exporter
    state: restarted
    daemon_reload: yes
